/*
 * AltaDetalleFacturaConRecibo.java
 *
 * Created on 23 de marzo de 2007, 15:57
 */

package vista;

import controlador.DetalleFactura;
import controlador.EjemplarLibro;
import controlador.Libro;
import java.util.LinkedList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author  PC
 */
public class AltaDetalleFacturaConRecibo extends javax.swing.JFrame {
    
    private NuevaFactura padre;
    /** Creates new form AltaDetalleFacturaConRecibo */
    public AltaDetalleFacturaConRecibo(NuevaFactura nf) {
        initComponents();
        this.padre = nf;
        precio.setText("$ " + String.valueOf(new Libro((String)comboLibro.getSelectedItem()).getPrecio()));
        this.setTitle("Detalle de factura - " + this.padre.getCliente().getNombre());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboLibro = new javax.swing.JComboBox();
        precio = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("Libro:");

        jLabel2.setText("Precio:");

        jLabel3.setText("Cantidad:");

        comboLibro.setModel(getModel());
        comboLibro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboLibroItemStateChanged(evt);
            }
        });

        precio.setText("$ -.--");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(precio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboLibroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboLibroItemStateChanged
        precio.setText("$ " + String.valueOf(new Libro((String)comboLibro.getSelectedItem()).getPrecio()));
        cantidad.setText("");
    }//GEN-LAST:event_comboLibroItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(((String)comboLibro.getSelectedItem()).compareTo("") == 0)
            JOptionPane.showMessageDialog(this, "Debe seleccionar un titulo", "Error", JOptionPane.ERROR_MESSAGE);
        else if(cantidad.getText().compareTo("") == 0)
            JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            Libro libro = new Libro((String)this.comboLibro.getSelectedItem()); //libro por titulo
            try{
                EjemplarLibro ejemplar = new EjemplarLibro(libro, libro.getPrecio());
                DetalleFactura def = new DetalleFactura(ejemplar, Integer.parseInt(cantidad.getText()), null, 0);
                this.padre.insertarFila(def);
                this.padre.setTotales();
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El formato de cantidad debe ser un numero entero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
   public ComboBoxModel getModel(){
        LinkedList lista = Libro.getLibros();
        String[] titulos = new String[lista.size()];
        for(int i = 0; i < lista.size() ; i++){
            titulos[i] = new String(((Libro)lista.get(i)).getTitulo());
        }
        cbm = new DefaultComboBoxModel(titulos);
        return cbm;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox comboLibro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
     private DefaultComboBoxModel cbm;
}
