/*
 * AltaDetalleFactura.java
 *
 * Created on 18 de marzo de 2007, 20:12
 */

package vista;

import controlador.DetalleFactura;
import controlador.DetalleRemito;
import controlador.DeudaRemito;
import controlador.EjemplarLibro;
import controlador.Remito;
import java.util.LinkedList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author  PC
 */
public class AltaDetalleFactura extends javax.swing.JFrame {
    
    private NuevaFactura padre;
    /** Creates new form AltaDetalleFactura */
    public AltaDetalleFactura(NuevaFactura nf) {
        this.padre = nf;
        initComponents();
        this.remito = null;
        this.setTitle("Detalle de factura - " + this.padre.getCliente().getNombre());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        comboRemito = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboItem = new javax.swing.JComboBox();
        comboCantidad = new javax.swing.JComboBox();
        precio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(getModalExclusionType());
        jLabel1.setText("Remito: ");

        comboRemito.setModel(getModeloRemito());
        comboRemito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboRemitoItemStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalle "));
        jLabel2.setText("Item: ");

        jLabel3.setText("Precio:");

        jLabel4.setText("Cantidad:");

        comboItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboItem.setEnabled(false);
        comboItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemItemStateChanged(evt);
            }
        });

        comboCantidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCantidad.setEnabled(false);
        comboCantidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCantidadItemStateChanged(evt);
            }
        });

        precio.setText("$ 0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio)
                    .addComponent(comboItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(comboRemito, 0, 195, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        switch(this.fase){
            case 0:
                JOptionPane.showMessageDialog(this,"Seleccione un remito.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 1: 
                JOptionPane.showMessageDialog(this,"Seleccione un titulo.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this,"Seleccione una cantidad .", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 3:
                DetalleFactura def = new DetalleFactura(this.ejemplar, this.cantidadElegida, null, detalleRemitoAsociado.getId() );
                padre.insertarFila(def);
                padre.setTotales();
                this.dispose();
            
                
                
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    //metodo que se llama cuando se selecciona una cantidad
    private void comboCantidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCantidadItemStateChanged
        String cantElegida = (String) comboCantidad.getSelectedItem();
        if(cantElegida.compareTo(" ") != 0 ) {
            this.fase = 3;
            this.cantidadElegida = Integer.parseInt(cantElegida);
        }
        else{
            this.fase = 2;
            this.cantidadElegida = 0;
        }
         
        return;
    }//GEN-LAST:event_comboCantidadItemStateChanged
    //metodo que se llama cuando se selecciona un titulo
    private void comboItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemItemStateChanged
            if(((String)comboItem.getSelectedItem()).compareTo(" ") == 0){
                comboCantidad.setEnabled(false);
                precio.setText("$ -.--" );
                return;
            }
            this.comboCantidad.setEnabled(true);
            LinkedList deudas = DeudaRemito.getDeudaXRemito(this.remito.getNumero());
            for(int i = 0; i < deudas.size() ; i++){
                //compara si cada titulo de libro del detalle es el elegido en el combo
                DeudaRemito deuda = (DeudaRemito)deudas.get(i) ;
                DetalleRemito detalle = deuda.getDetalleRemito();
                if (detalle.getEjemplar().getLibro().getTitulo().compareTo((String)comboItem.getSelectedItem()) == 0){
                    this.ejemplar = detalle.getEjemplar();
                    this.cantidad = deuda.getCantidad(); //la cantidad que queda en la deuda
                    this.precio.setText("$ " + detalle.getEjemplar().getPrecioUnitario());
                    this.detalleRemitoAsociado = detalle;
                }
            }
            this.comboCantidad.setModel(this.getModeloCant());
            this.fase = 2;
            return;                
    }//GEN-LAST:event_comboItemItemStateChanged
    //metodo q se llama cuando se selecciona un remito    
    private void comboRemitoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboRemitoItemStateChanged
        if(((String)comboRemito.getSelectedItem()).compareTo(" ") == 0){
                comboItem.setEnabled(false);
                comboCantidad.setEnabled(false);
                precio.setText("$ -.--" );
                fase = 0;
                return;
        }
        String elegido = (String) comboRemito.getSelectedItem();
        this.remito = new Remito(elegido);
        comboItem.setModel(getModeloItem());
        comboItem.setEnabled(true);
        comboCantidad.setEnabled(false);    
        this.fase = 1;
        return;
    }//GEN-LAST:event_comboRemitoItemStateChanged
    
   public ComboBoxModel getModeloRemito(){
        LinkedList lista = Remito.getRemitosPendientes(this.padre.getCliente().getId());
        String[] numeros = new String[lista.size()+1];
        numeros[0] = new String(" ");
        for(int i = 0; i < lista.size() ; i++){
            numeros[i+1] = new String(((Remito)lista.get(i)).getNumero());
        }
        cbmRemito = new DefaultComboBoxModel(numeros);
        
        return cbmRemito;
    }
   //crea el modelo si se selecciono un remito
   public ComboBoxModel getModeloItem(){
       LinkedList lista = DeudaRemito.getDeudaXRemito(this.remito.getNumero());
       String[] titulos = new String[lista.size()+1];
       titulos[0] = " ";
       for(int i = 0; i < lista.size() ; i++){
            titulos[i+1] = new String(((DeudaRemito)lista.get(i)).getDetalleRemito().getEjemplar().getLibro().getTitulo());
       }
       cbmItem = new DefaultComboBoxModel(titulos);
       return cbmItem;
   }
   
   public ComboBoxModel getModeloCant(){
       String[] vectorCantidad = new String[this.cantidad+1] ;
       int i;
       vectorCantidad[0] = " ";
       for (i = 0; i < cantidad ; i++){
           vectorCantidad[i+1] = String.valueOf(i+1);
       }
       cbmCant = new DefaultComboBoxModel(vectorCantidad);
       //cbmCant.setSelectedItem(String.valueOf(i+1));
       return cbmCant;
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCantidad;
    private javax.swing.JComboBox comboItem;
    private javax.swing.JComboBox comboRemito;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel cbmRemito;
    private DefaultComboBoxModel cbmItem; 
    private DefaultComboBoxModel cbmCant;
    private boolean conRemito;
    private Remito remito;
    private int cantidad = 0;
    private int fase = 0;
    private EjemplarLibro ejemplar;
    private int cantidadElegida;
    private DetalleRemito detalleRemitoAsociado;
}

