/*
 * Liquidacion.java
 *
 * Created on 31 de marzo de 2007, 19:51
 */

package vista;

import controlador.Cliente;
import controlador.DetalleFactura;
import controlador.DetalleRemito;
import controlador.DeudaFactura;
import controlador.DeudaRemito;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.TimeZone;

   

/**
 *
 * @author  PC
 */
public class Liquidacion extends javax.swing.JFrame {
    
    /** Creates new form Liquidacion */
    public Liquidacion(Cliente cli) {
        this.cliente = cli;
        initComponents();
        liquidar();
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liquidaci\u00f3n");
        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html");
        jEditorPane1.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEditorPane1HyperlinkUpdate(evt);
            }
        });

        jScrollPane1.setViewportView(jEditorPane1);

        jButton1.setText("Cerrar");

        jButton2.setText("Guardar a archivo");

        jButton3.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEditorPane1HyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_jEditorPane1HyperlinkUpdate
       
    }//GEN-LAST:event_jEditorPane1HyperlinkUpdate
    public static String getFecha() {
      String fecha;
      Calendar cal = Calendar.getInstance(TimeZone.getDefault());
      String FORMATOHORA = "dd/MM/yy";
      java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(FORMATOHORA);
      fecha = sdf.format(cal.getTime());
      return fecha;
      }
    public void liquidar(){
        this.contenido = "<html>" +
                "<head>" +
                "<style type=\"text/css\">" +
                "#central {width : 700px;}" +
                ".main {width : 100%; margin-left : 15px;}" +
                ".remito { width:100%;  border : 0px; margin-left : 10px;margin-top:0px;}" +
                ".remito td {width:20%; align: right; }" +
                ".factura { width:100%;  border : 0px; margin-left : 10px;margin-top:0px;}" +
                ".factura td {width:20%;  }" +
                "#cli  { font-weight : bold ;} " +
                ".main table tr.cabeza{font-weight : bold;}" +
                ".main table tr.total{font-weight : bold;}" +
                "<style></head> <body >" +
                "<div id=\"central\">" +
                "<center><h1>Ferreyra Editor</h1><h2>Liquidación al " + getFecha() + "</h2></center><br/>" +
                "<h2 id =\"cli\" >Cliente: " + cliente.getNombre() + "</h2>" +
                "<h4 id=\"dir\">" + cliente.getDireccion() + " - " + cliente.getEmail() + "</h4><hr/><br/>" ;
        this.contenido += getTablaRemitos();
        this.contenido += "</body></html>";
        System.out.println(total);
    }
    
    public String getTablaRemitos(){
        LinkedList deudas = cliente.getDeudas();
        
        String  temp ;
        String numRAnterior = "";
        String numFAnterior = "";
        temp = "";
        
        for(int i = 0; i < deudas.size(); i++){
             try{
                DeudaRemito dr = (DeudaRemito)deudas.get(i);
                if(numRAnterior.compareTo(dr.getNumeroRemito()) == 0 ){
                    temp += getLineaRem(dr);
                }
                else{
                    if(numRAnterior.compareTo("") != 0){
                        temp += getPieRem();
                    }
                    numRAnterior = dr.getNumeroRemito();
                    temp += getCabezaRem(dr); //incluye la primer linea (getLineaRem)
                }   
                
             }catch(ClassCastException e){
                DeudaFactura def = (DeudaFactura)deudas.get(i);
                if(numFAnterior.compareTo(def.getNumeroFactura()) == 0 ){
                    temp += getLineaFac(def);
                }
                else{
                    if(numFAnterior.compareTo("") != 0){
                        temp += getPieFac();
                    }
                    numFAnterior = def.getNumeroFactura();
                    temp += getCabezaFac(def); //incluye la primer linea (getLineaFac)
                }   
             }
             
        }
        return temp;
    }
    
    public String getCabezaRem(DeudaRemito dr ) {
        String cabeza;
        cabeza = "<div class=\"main\"> " +
                "<h3> Remito nro " + dr.getNumeroRemito() + "</h3>" + 
                "<table class =\"remito\"> " +
                "   <tr class=\"cabeza\"> " +
                "       <td> Titulo </td> " +
                "       <td> Precio </td> " +
                "       <td> Cantidad </td> " +
                "       <td> Subtotal </td> " +
                "   </tr> \n";
        return cabeza + getLineaRem(dr);
    }
    public String getLineaRem(DeudaRemito dr){
        String temp ;
        DetalleRemito det = dr.getDetalleRemito();
        this.totalRemito += det.getEjemplar().getPrecioUnitario() * dr.getCantidad() ;
        temp = "<tr>" +
               "    <td> " + det.getEjemplar().getLibro().getTitulo() + "</td>" +
               "    <td> " + det.getEjemplar().getPrecioUnitario() + "</td> " +
               "    <td> " + dr.getCantidad() + " </td> " +
               "    <td> " + dr.getTotal() + "</td> " +
               "</tr>"; 
        return temp;        
    }
    public String getPieRem(){
        String temp;
        temp = "<tr class=\"total\"><td></td><td></td><td>Total</td><td>" + this.totalRemito + "</td></tr>" +
                "</table> </div>\n" ;
        this.total += totalRemito;
        this.totalRemito = 0;
        return temp;
    }
    public String getCabezaFac (DeudaFactura d ) {
        String cabeza;
        cabeza = "<div class=\"main\"> " +
                "<h3> Factura  A " + d.getNumeroFactura() + "</h3>" + 
                "<table class =\"factura\"> " +
                "   <tr class=\"cabeza\"> " +
                "       <td> Titulo </td> " +
                "       <td> Precio </td> " +
                "       <td> Cantidad </td> " +
                "       <td> Subtotal </td> " +
                "   </tr> \n";
        return cabeza + getLineaFac(d);
    }
    public String getLineaFac(DeudaFactura d){
        String temp ;
        DetalleFactura det = d.getDetalleFactura();
        this.totalFactura += det.getEjemplar().getPrecioUnitario() * d.getCantidad() ;
        temp = "<tr>" +
               "    <td> " + det.getEjemplar().getLibro().getTitulo() + "</td>" +
               "    <td> " + det.getEjemplar().getPrecioUnitario() + "</td> " +
               "    <td> " + d.getCantidad() + " </td> " +
               "    <td> " + d.getTotal() + "</td> " +
               "</tr>"; 
        return temp;        
    }
    public String getPieFac (){
        String temp;
        temp = "<tr class=\"total\"><td></td><td></td><td>Total</td><td>" + this.totalFactura + "</td></tr>" +
                "</table> </div>\n" ;
        this.total = totalFactura;
        this.totalFactura = 0;
        
        return temp;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private String contenido;
    private Cliente cliente;
    private String numFAnterior ;
    private String numRAnterior;
    private float totalRemito = 0;
    private float totalFactura = 0;
    private float total = 0;
}
