/*
 * NuevaFactura.java
 *
 * Created on 18 de marzo de 2007, 18:42
 */

package vista;

import controlador.Cliente;
import controlador.DetalleFactura;
import controlador.DetalleRemito;
import controlador.DeudaRemito;
import controlador.EjemplarLibro;
import controlador.Factura;
import controlador.FacturaConRecibo;
import controlador.Libro;
import controlador.Main;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  PC
 */
public class NuevaFactura extends javax.swing.JFrame {
    
    private VentanaFacturas padre;
    private Cliente cliente;
    private Factura factura;
    private FacturaConRecibo facturaConRecibo;
    
    /** Creates new form NuevaFactura */
    public NuevaFactura(VentanaFacturas vf, Cliente cli) {
        this.cliente = cli;
        this.padre = vf;
        initTabla();
        initComponents();
        //comision.setText("( " + String.valueOf(cliente.getComision()) + "% )");
        this.setTitle("Registrar factura para " + cliente.getNombre());
        this.radioPagado.setSelected(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        numero = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bruto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        neto = new javax.swing.JLabel();
        descuento = new javax.swing.JLabel();
        comision = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        radioPagado = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaComision = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("Tipo:");

        jLabel2.setText("N\u00famero:");

        jLabel3.setText("Fecha: ");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "M" }));

        jLabel5.setText("/");

        jLabel6.setText("/");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalle de factura"));
        jScrollPane1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jScrollPane1ComponentAdded(evt);
            }
        });

        jTable1.setModel(getModel());
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        jLabel4.setText("Total a cobrar:   ");

        bruto.setText("0.0");

        jLabel7.setText("Total Bruto: ");

        jLabel8.setText("Descuento comisi\u00f3n: ");

        neto.setText("0.0");

        descuento.setText("0.0");

        comision.setText("( com )");

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Registrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        radioPagado.setText("Factura pagada (con remito)");
        radioPagado.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioPagado.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioPagado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioPagadoItemStateChanged(evt);
            }
        });

        jLabel9.setText("$");

        jLabel10.setText("$");

        jLabel11.setText("$");

        jLabel12.setText("Comision:");

        listaComision.setModel(getModeloLista());
        listaComision.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaComision.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaComisionValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(listaComision);

        jLabel13.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)))
                    .addComponent(numero))
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(neto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(descuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bruto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comision, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(radioPagado, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioPagado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bruto)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descuento)
                            .addComponent(jLabel9)
                            .addComponent(comision))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(neto)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaComisionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaComisionValueChanged
        comision.setText("( " + (String)listaComision.getSelectedValue() + "% )");
        this.valorComision = Integer.parseInt((String) this.listaComision.getSelectedValue());
    }//GEN-LAST:event_listaComisionValueChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(dtm.getRowCount() == 0)
            JOptionPane.showMessageDialog(this,"Debe ingresar un detalle de factura como mínimo", "Error", JOptionPane.ERROR_MESSAGE);
        else if (dia.getText().compareTo("") == 0 || mes.getText().compareTo("") == 0 || ano.getText().compareTo("") == 0)
            JOptionPane.showMessageDialog(this,"Debe ingresar una fecha", "Error", JOptionPane.ERROR_MESSAGE);
        else if(numero.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(this,"Debe ingresar un numero de Remito", "Error", JOptionPane.ERROR_MESSAGE);
            try{
                Integer.parseInt(numero.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this,"El número de remito solo debe contener enteros.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try{
                int d = Integer.parseInt(dia.getText());
                int m = Integer.parseInt(mes.getText());
                int a = Integer.parseInt(ano.getText());
                if(d < 1 || d > 31 || m < 1 || m > 12 | a < 1980)
                    Integer.parseInt("a"); //throw NumberFormatException;
            }catch(NumberFormatException er){
                JOptionPane.showMessageDialog(this,"Error en el formato de la fecha.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        else if(Factura.existeId(numero.getText(), (String)comboTipo.getSelectedItem())){
            JOptionPane.showMessageDialog(this,"El numero de factura ingresado ya existe en la Base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            if(((String)listaComision.getSelectedValue()).compareTo("0") == 0){
                int nro ;
                nro = JOptionPane.showConfirmDialog(this, "La comision que esta ingresando es un valor nulo\nDesea de todas formas registrar la factura?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(nro == 1)
                    return;
            }
            if(radioPagado.isSelected()){
                //empieza el alta de factura con remito, es decir, sinrecibo
                this.factura = new Factura(numero.getText(), (String)comboTipo.getSelectedItem(), Main.getHora(Integer.parseInt(ano.getText()), Integer.parseInt(mes.getText()), Integer.parseInt(dia.getText())), this.cliente, Float.parseFloat((String)listaComision.getSelectedValue()), this.radioPagado.isSelected());
                factura.hacerAlta();
                Libro libro;
                EjemplarLibro ejemplar;
                int cantidad;
                for(int i = 0; i < dtm.getRowCount(); i++){
                    libro = new Libro((Integer)jTable1.getValueAt(i, 1));
                    ejemplar = new EjemplarLibro(libro, libro.getPrecio());
                    ejemplar.hacerAlta(); //si el ejemplar ya existe, no hace el alta
                    cantidad = (Integer)jTable1.getValueAt(i, 4);
                    
                    ////////////////
                    DetalleRemito detalle = null;
                    LinkedList deudas = DeudaRemito.getDeudaXRemito((String)jTable1.getValueAt(i, 0));
                    for(int j = 0; j < deudas.size() ; j++){
                        //compara si cada titulo de libro del detalle es el elegido en el combo
                        DeudaRemito deuda = (DeudaRemito)deudas.get(j) ;
                        if (deuda.getDetalleRemito().getEjemplar().getLibro().getTitulo().compareTo((String)jTable1.getValueAt(i, 2)) == 0){
                            detalle = deuda.getDetalleRemito();
                        }
                    }
                    //////////////
                    DetalleFactura df = new DetalleFactura(ejemplar, cantidad, this.factura, detalle.getId());
                    df.hacerAlta();
                    
                }
                factura.setTotal(Float.parseFloat(bruto.getText()));
                this.padre.insertarFila(this.factura);
                this.dispose();
                
            }
            else {
                this.factura = new FacturaConRecibo(numero.getText(), (String)comboTipo.getSelectedItem(), Main.getHora(Integer.parseInt(ano.getText()), Integer.parseInt(mes.getText()), Integer.parseInt(dia.getText())), this.cliente, Float.parseFloat((String)listaComision.getSelectedValue()), false);
                factura.hacerAlta();
                Libro libro;
                EjemplarLibro ejemplar;
                int cantidad;
                for(int i = 0; i < dtm.getRowCount(); i++){
                    libro = new Libro((Integer)jTable1.getValueAt(i, 0));
                    ejemplar = new EjemplarLibro(libro, libro.getPrecio());
                    ejemplar.hacerAlta(); //si el ejemplar ya existe, no hace el alta
                    cantidad = (Integer)jTable1.getValueAt(i, 3);
                    DetalleFactura dr = new DetalleFactura(ejemplar, cantidad, this.factura, 0); //con id de detalle de remito 0, es conr ecibo
                    dr.hacerAlta();
                }
                factura.setTotal(Float.parseFloat(bruto.getText()));
                this.padre.insertarFila(this.factura);
                this.dispose();
                
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void radioPagadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioPagadoItemStateChanged
        this.actualizarModelo();
    }//GEN-LAST:event_radioPagadoItemStateChanged

    private void jScrollPane1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentAdded
        
    }//GEN-LAST:event_jScrollPane1ComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(radioPagado.isSelected() == false){
            AltaDetalleFacturaConRecibo adfcr = new AltaDetalleFacturaConRecibo(this);
            adfcr.setVisible(true);
        }
        else{
            AltaDetalleFactura adf = new AltaDetalleFactura(this);
            adf.setVisible(true);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila = jTable1.getSelectedRow();
        if (!borrarFila()){
            JOptionPane.showMessageDialog(this, "Seleccione un elemento a borrar.", "No hay ningun libro seleccionado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(dtm.getRowCount() == 0)
            radioPagado.setEnabled(true);  
        this.setTotales();
        return;            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void setTotales(){
        int columnaTotal = 4; //por defecto 4
        if(radioPagado.isSelected()){
            columnaTotal = 5; //si es con remito, lo cambio a 5
        }
        float temp = 0;
        for(int i = 0; i < dtm.getRowCount() ; i++){
            temp += (Float)jTable1.getValueAt(i, columnaTotal);
        }
        this.bruto.setText(String.valueOf(temp));
        float desc = (temp * ((float)this.valorComision / 100));
        this.descuento.setText(String.valueOf(desc) );
        this.neto.setText(String.valueOf(temp - desc));
    }
    public DefaultTableModel getModel(){
        return this.dtm;
    }
    public DefaultListModel getModeloLista(){
        dlm = new DefaultListModel();
        for(int i = 0; i <= 100; i += 5){
            dlm.addElement(String.valueOf(i));
        }
        return dlm;
    }
    public void initTabla(){
        dtm = new DefaultTableModel();
        dtm.addColumn("Remito");
        dtm.addColumn("Cod");
        dtm.addColumn("Titulo");
        dtm.addColumn("Precio");
        dtm.addColumn("Cant.");
        dtm.addColumn("Subtotal");
    }
    public void actualizarModelo(){
        dtm= new DefaultTableModel();
        if(radioPagado.isSelected()){
            dtm.addColumn("Remito");
            dtm.addColumn("Cod");
            dtm.addColumn("Titulo");
            dtm.addColumn("Precio");
            dtm.addColumn("Cant.");
            dtm.addColumn("Subtotal");
        }
        else{
            dtm.addColumn("Cod");
            dtm.addColumn("Titulo");
            dtm.addColumn("Precio");
            dtm.addColumn("Cant.");
            dtm.addColumn("Subtotal");
        }
        jTable1.removeAll();
        jTable1.setModel(dtm);
    }
    private Object[] getFila(DetalleFactura def){
        Object[] datos;
        if(def.getIdDetalleRemito() != 0){
            datos = new Object[6];
            datos[0] = new DetalleRemito(def.getIdDetalleRemito()).getRemito().getNumero();
            datos[1] = def.getEjemplar().getLibro().getId();
            datos[2] = def.getEjemplar().getLibro().getTitulo();
            datos[3] = def.getEjemplar().getPrecioUnitario();
            datos[4] = def.getCantidad(); //es la cantidad elegida
            datos[5] = (def.getEjemplar().getPrecioUnitario() * def.getCantidad());
        }
        else{
            datos = new Object[5];
            datos[0] = def.getEjemplar().getLibro().getId();
            datos[1] = def.getEjemplar().getLibro().getTitulo();
            datos[2] = def.getEjemplar().getPrecioUnitario();
            datos[3] = def.getCantidad();
            datos[4] = (def.getEjemplar().getPrecioUnitario() * def.getCantidad());            
        }
        return datos;
    }
    public void insertarFila(DetalleFactura def){
        this.dtm.addRow(getFila(def));
        radioPagado.setEnabled(false);
    }
    public boolean borrarFila(){
        if(jTable1.getSelectedRow() != -1){
            this.dtm.removeRow(jTable1.getSelectedRow());
            return true;
        }
        
        
        return false;
    }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano;
    private javax.swing.JLabel bruto;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JLabel comision;
    private javax.swing.JLabel descuento;
    private javax.swing.JTextField dia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList listaComision;
    private javax.swing.JTextField mes;
    private javax.swing.JLabel neto;
    private javax.swing.JTextField numero;
    private javax.swing.JRadioButton radioPagado;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel dtm;
    private DefaultListModel dlm;
    private int valorComision;
    
    public Cliente getCliente(){
        return this.cliente;
    }
}
